### ISSUE TITLE
Incorrect order price shown 

### ISSUE THREAD

**Issue by fedgiac** [gnosis/dex-telegram#174]
The last orders I created on Rinkeby for the pair WETH/USDC had (partially) incorrect prices reported by the Telegram bot. The prices were right when shown as 1 WETH = x USDC, but they were incorrect in the case 1 USDC = x WETH. This happened for both sell and buy orders.

Example:
```
[dev] Gnosis Protocol
Sell USDC for WETH

- Price: 1 USDC = 0.72041605764147309 WETH
- Price: 1 WETH = 138.8086772071461040418 USDC
- Tradable: Today at 11:50 AM GMT, in 11 minutes
- Expires: Valid until cancelled

Fill the order here: https://dex.dev.gnosisdev.com/trade/WETH-USDC?sell=0&price=138.5310598527318118337
```
The price I used is ~138.8. What I'd expect is:
```
[...]
- Price: 1 USDC = 0.007204161 WETH
[...]
```

Pictures with some orders with this issue:
![weth-usdc-orders](https://user-images.githubusercontent.com/58218759/77644695-55c57d80-6f59-11ea-990d-b7255fd04403.png)

**Comment by alfetopito** [comment]
Thanks for reporting @fedgiac 
Will soon have the fix ready for telegram and web.
