### ISSUE TITLE
[Rinkeby] Maybe sUSD and Maybe sETH

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-telegram#185]
Addresses for both `sUSD` and `sETH` are included in the https://github.com/gnosis/dex-js/blob/master/src/tokenList.json
file on rinkeby and mainnet, but the telegram-bot still says "maybe sETH" and "maybe sUSD". NOt sure if there is some other logic governing whether or not telegram-bot knows the tokens or not.

<img width="482" alt="Screenshot 2020-04-07 at 7 42 51 PM" src="https://user-images.githubusercontent.com/11778116/78643191-f88ddc80-7907-11ea-80e0-ae6b7bf7faf8.png">

**Comment by anxolin** [comment]
There shouldn't, if it's updated to the dex-js version it should, it must not say "maybe"

Could it be a case-sensitivity issue?

**Comment by alfetopito** [comment]
Keep in mind sETH and sUSD are not registered in the Rinkeby contract, at least not with the same ids as Mainnet. This _might_ be the cause.

**Comment by anxolin** [comment]
ahhhhhh, rinkeby. Thanks @alfetopito !

**Comment by bh2smith** [comment]
I registered them! We wouldn’t be able to place orders if they weren’t registered.

**Comment by alfetopito** [comment]
> I registered them! We wouldn’t be able to place orders if they weren’t registered.

Good point.

This flag is what controls the token's `Maybe` flag: https://github.com/gnosis/dex-telegram/blob/93c888be4fdfd4a3d74db78094a204cd68995607/src/services/DfusionService.ts#L263

Best guess is what @anxolin mentioned, the case.
If you are at it, you can try to lower case both on this comparison https://github.com/gnosis/dex-telegram/blob/93c888be4fdfd4a3d74db78094a204cd68995607/src/services/DfusionService.ts#L256

**Comment by bh2smith** [comment]
They both appear to be there in mixed-case just like all the others...

https://github.com/gnosis/dex-js/blob/108c11d34210fb2ec231dc57a1f47898f789f179/src/tokenList.json#L93-L118

**Comment by alfetopito** [comment]
What's the address you registered for `sETH` on rinkeby?

Using the one from here [0xA83AbFdC9E8Ee990C3C6C0f56a4B06e0faAd583C](https://github.com/gnosis/dex-js/blob/108c11d34210fb2ec231dc57a1f47898f789f179/src/tokenList.json#L100)

Checking against the rinkeby contract (https://rinkeby.etherscan.io/address/0xC576eA7bd102F7E476368a5E98FA455d1Ea34dE2#readContract) on the function `hasToken` I get `false`.

**Comment by alfetopito** [comment]
Nope, same contract on the bot (0xC576eA7bd102F7E476368a5E98FA455d1Ea34dE2)

![screenshot_2020-04-08_11-56-24](https://user-images.githubusercontent.com/43217/78822471-f707f700-798f-11ea-964a-b1e3592c899e.png)

**Comment by alfetopito** [comment]
I don't know the reason why we got this address, but I got the reason why it's *Maybe*:

List of tokens (from https://thegraph.com/explorer/subgraph/gnosis/protocol-rinkeby):

query:
```
{
  tokens(where: {symbol: "sETH"}) {
    id
    address
    symbol
  }
}
```

result:
```
{
  "data": {
    "tokens": [
      {
        "address": "0x0647b2c7a2a818276154b0fc79557f512b165bc1",
        "id": "12",
        "symbol": "sETH"
      }
    ]
  }
}
```

Address on our list for `sETH` on Rinkeby: https://github.com/gnosis/dex-js/blob/108c11d34210fb2ec231dc57a1f47898f789f179/src/tokenList.json#L100: `0xA83AbFdC9E8Ee990C3C6C0f56a4B06e0faAd583C`

Blame!! (love this :D) https://github.com/gnosis/dex-js/commit/9496f2d05d5d1f719bacb1181c3aec6a5c5d73b6

**Comment by alfetopito** [comment]
There ya go https://github.com/gnosis/dex-js/pull/134
