### ISSUE TITLE
Not all orders are shown.

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-telegram#187]
When we are deploying a new liquidity strategy, we mine many orders, up to 22 in one block. Usually, only half of them are shown in telegram. I am not aware of what could cause this loss.

Here is one part of the display in telegram:
https://t.me/gnosis_protocol/5729

But the etherscan transaction has 22 orders:
https://etherscan.io/tx/0x214d1165a0a359da50f5d449477d9fe7e8bd614a4a531409fe4c87f7663147d7

**Comment by anxolin** [comment]
Sorry @josojo I just saw this one now. 
@Velenir is dealing with this issue to make the bot a bit more robust. 
The error is due to a rate limit we hit. 

On monday, he is releasing a new version. Let us know if the issue persist. Thanks!!

**Comment by Velenir** [comment]
Bot successfully handled a full liquidity order (42 actual orders through UI). Should be ok handling even more.
So I'm closing this for now
