### ISSUE TITLE
Link to fill orders doesn't reverse token pair

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-telegram#78]
The following two screen shots show that the link takes the "user" to the order page with the correct numbers, but not reversed tokens.

<img width="541" alt="Screenshot 2019-12-27 at 09 50 28" src="https://user-images.githubusercontent.com/11778116/71510544-94cb3080-288f-11ea-9715-6ed0b22cad61.png">

<img width="448" alt="Screenshot 2019-12-27 at 09 58 11" src="https://user-images.githubusercontent.com/11778116/71510556-985eb780-288f-11ea-8bbc-004d003bf77f.png">

**Comment by anxolin** [comment]
Thanks for reporting, yep, that's right!
