### ISSUE TITLE
Automated fill has the token the wrong way around

### ISSUE THREAD

**Issue by c3rnst** [gnosis/dex-telegram#85]
![Screenshot 2020-01-02 at 17 37 02](https://user-images.githubusercontent.com/34367524/71678888-85b01b00-2d86-11ea-948c-ef68d3b0866a.png)

The telegram bot is set up the wrong way around for the auto fill suggestion.
E.g. see attachment --> once clicking on "fill the order here" link, it shows up the wrong way around on the interface.

**Comment by anxolin** [comment]
Yep! it was reported and Ben did a fix to that. Thanks Chris
